apiVersion: argoproj.io/v1alpha1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: platform-ns-rbac
      namespace: argocd
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source:
        repoURL: https://github.com/<ORG>/project-hybrid_platform_gitops
        targetRevision: main
        path: clusters/prod-apne2/apps/ns-rbac
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true]

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: platform-alb-controller
      namespace: argocd
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      source:
        repoURL: https://aws.github.io/eks-charts
        chart: aws-load-balancer-controller
        targetRevision: 1.8.1
        helm:
          values: |
            clusterName: test-mh-eks-cluster
            region: ap-northeast-2
            vpcId: <VPC_ID>
            serviceAccount:
              create: true
              name: aws-load-balancer-controller
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/AmazonEKSLoadBalancerControllerRole
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true]
