apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# 이미지는 오버레이에서 override.
images:
  - name: app
    newName: app
    newTag: "latest"
